version: 2

project_name: gpipe

before:
  hooks:
    - go mod tidy

builds:
  - id: gpipe
    main: .
    binary: gpipe
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - -s -w
      - -X github.com/thomaslaurenson/gpipe/cmd.Version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: gpipe
    formats: [binary]
    name_template: >-
      gpipe-
      {{- if eq .Os "linux"}}linux
      {{- else if eq .Os "darwin"}}macos
      {{- else if eq .Os "windows"}}windows
      {{- end}}-
      {{- if eq .Arch "amd64"}}x86_64
      {{- else if eq .Arch "arm64"}}aarch64
      {{- end}}

checksum:
  name_template: checksums.txt
  algorithm: sha256

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --output-certificate=${certificate}
      - --output-signature=${signature}
      - ${artifact}
    artifacts: checksum
    output: true

changelog:
  sort: desc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
