binary: gpipe

platforms:
  linux_amd64:
    path: ./dist/gpipe-linux-x86_64
    name: gpipe-linux-x86_64
  linux_arm64:
    path: ./dist/gpipe-linux-aarch64
    name: gpipe-linux-aarch64
  darwin_amd64:
    path: ./dist/gpipe-darwin-x86_64
    name: gpipe-darwin-x86_64
  darwin_arm64:
    path: ./dist/gpipe-darwin-aarch64
    name: gpipe-darwin-aarch64
  windows_amd64:
    path: ./dist/gpipe-windows-x86_64.exe
    name: gpipe-windows-x86_64.exe
