#!/usr/bin/env bash

# Generated by gpipe: https://github.com/thomaslaurenson/gpipe
# Do not edit manually. Re-generate with: gpipe generate --repo <owner/repo> --version <vX.Y.Z>

# Wrapping the script body in a brace block causes the shell to buffer the
# complete download before starting execution, preventing partial runs if the
# connection drops mid-pipe.
{
# set -euo pipefail is intentionally inside the brace block so it applies
# only after the download guard is established.
set -euo pipefail

# ============================================================
# CONSTANTS: baked in at generation time
# ============================================================
readonly GITHUB_REPO="{{.GithubRepo}}"
readonly VERSION="{{.Version}}"
readonly BINARY="{{.Binary}}"
readonly INSTALL_NAME="{{.InstallName}}"

# ============================================================
# OUTPUT HELPERS
# ============================================================
# Check stdout (fd 1) for colour support
if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]] && [[ "${TERM:-}" != "dumb" ]]; then
  _RED='\033[0;31m' _GREEN='\033[0;32m' _YELLOW='\033[1;33m'
  _CYAN='\033[0;36m' _BOLD='\033[1m' _NC='\033[0m'
else
  _RED='' _GREEN='' _YELLOW='' _CYAN='' _BOLD='' _NC=''
fi

info()  { printf "${_GREEN}[INFO]${_NC}  %s\n" "$1"; }
warn()  { printf "${_YELLOW}[WARN]${_NC}  %s\n" "$1" >&2; }
error() { printf "${_RED}[ERROR]${_NC} %s\n" "$1" >&2; exit 1; }
step()  { printf "  ${_CYAN}>${_NC} %s\n" "$1"; }

# ============================================================
# USAGE
# ============================================================
show_help() {
  cat <<EOF
${_BOLD}${INSTALL_NAME} installer${_NC}

USAGE:
  bash install.sh [OPTIONS]

OPTIONS:
  -h, --help      Show this help message
  --user          Install to ~/.local/bin (no sudo required)
  --system        Install to /usr/local/bin (default, may require sudo)
  --no-verify     Skip cosign signature verification on checksums.txt
                  By default, the installer verifies the release signature
                  using cosign. Use this flag only if cosign is unavailable.
                  Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/

EXAMPLES:
  # System-wide install (default)
  curl -fsSL https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh | bash

  # User-local install, no sudo needed
  curl -fsSL https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh | bash -s -- --user

  # Skip cosign verification (not recommended)
  curl -fsSL https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh | bash -s -- --no-verify

EOF
}

# ============================================================
# ARGUMENT PARSING
# ============================================================
USER_INSTALL=false
NO_VERIFY=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)    show_help; exit 0 ;;
    --user)       USER_INSTALL=true;  shift ;;
    --system)     USER_INSTALL=false; shift ;;
    --no-verify)  NO_VERIFY=true;     shift ;;
    *)            error "Unknown option: $1. Run with --help for usage." ;;
  esac
done

# ============================================================
# PLATFORM DETECTION
# ============================================================
_OS="$(uname -s)"
_ARCH="$(uname -m)"

case "$_OS" in
  Linux)  OS="linux"  ;;
  Darwin) OS="darwin" ;;
  *)      error "Unsupported operating system: ${_OS}" ;;
esac

case "$_ARCH" in
  x86_64)        ARCH="amd64" ;;
  aarch64|arm64) ARCH="arm64" ;;
  *)             error "Unsupported architecture: ${_ARCH}" ;;
esac

PLATFORM="${OS}_${ARCH}"

# ============================================================
# ASSET MAP: baked in at generation time
# Maps platform identifier to GitHub release asset filename.
# Uses a case statement for bash 3.2+ compatibility (macOS ships bash 3.2).
# ============================================================
case "$PLATFORM" in
{{- range .Platforms}}
  {{.ID}}) ASSET_NAME="{{.AssetName}}" ;;
{{- end}}
  *) error "Unsupported platform: ${PLATFORM}. Supported platforms: $(echo '{{range .Platforms}}{{.ID}} {{end}}' | xargs)" ;;
esac

DOWNLOAD_URL="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/${ASSET_NAME}"
CHECKSUMS_URL="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/checksums.txt"
CHECKSUMS_SIG_URL="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/checksums.txt.sigstore.json"

{{- if .Hooks.PreSh}}

# ============================================================
# PRE-INSTALL HOOK
# Injected from config at generation time.
# Available variables: GITHUB_REPO, VERSION, BINARY, INSTALL_NAME
# Note: hook runs in a subshell. set -euo pipefail is inherited.
# ============================================================
# --- gpipe: pre-install hook ---
(
{{.Hooks.PreSh}}
)
# --- gpipe: end pre-install hook ---
{{- end}}

# ============================================================
# DOWNLOAD
# ============================================================
_TMPDIR="$(mktemp -d)"
trap 'rm -rf "$_TMPDIR"' EXIT

# Prefer curl, fall back to wget. Tool preference is detected once.
if command -v curl > /dev/null 2>&1; then
  _download() {
    curl -fsSL --connect-timeout 30 --speed-limit 1024 --speed-time 30 "$1" -o "$2"
  }
elif command -v wget > /dev/null 2>&1; then
  _download() {
    wget --connect-timeout=30 --timeout=30 -qO "$2" "$1"
  }
else
  error "curl or wget is required to download files"
fi

info "Downloading ${BINARY} ${VERSION} for ${PLATFORM}..."
step "${DOWNLOAD_URL}"
_download "${DOWNLOAD_URL}"        "${_TMPDIR}/${ASSET_NAME}"
_download "${CHECKSUMS_URL}"       "${_TMPDIR}/checksums.txt"
_download "${CHECKSUMS_SIG_URL}"   "${_TMPDIR}/checksums.txt.sigstore.json"

# ============================================================
# COSIGN SIGNATURE VERIFICATION
# Verifies checksums.txt was produced by the official release
# workflow before trusting any checksum values.
# Use --no-verify to skip (not recommended).
# ============================================================
if [[ "$NO_VERIFY" == "true" ]]; then
  warn "Skipping cosign signature verification (--no-verify passed)"
else
  if ! command -v cosign > /dev/null 2>&1; then
    error "cosign not found in PATH.

  The installer verifies release signatures by default to ensure
  the download has not been tampered with. cosign is required for this.

  Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/

  To skip verification (not recommended):
    curl -fsSL https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh | bash -s -- --no-verify"
  fi
  info "Verifying cosign signature on checksums.txt..."
  cosign verify-blob \
    --bundle "${_TMPDIR}/checksums.txt.sigstore.json" \
    --certificate-identity-regexp="https://github.com/{{.GithubRepo}}/.github/workflows/.*" \
    --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
    "${_TMPDIR}/checksums.txt" || error "cosign signature verification failed"
  step "Cosign signature OK"
fi

# ============================================================
# CHECKSUM VERIFICATION
# Verifies the downloaded binary against the (now trusted) checksums.txt.
# The two-space separator is part of the sha256sum format.
# ============================================================
info "Verifying checksum..."
EXPECTED_HASH="$(grep -F "  ${ASSET_NAME}" "${_TMPDIR}/checksums.txt" | awk '{print $1}')"
if [[ -z "$EXPECTED_HASH" ]]; then
  error "Checksum not found for ${ASSET_NAME} in checksums.txt"
fi

if command -v sha256sum > /dev/null 2>&1; then
  ACTUAL_HASH="$(sha256sum "${_TMPDIR}/${ASSET_NAME}" | awk '{print $1}')"
elif command -v shasum > /dev/null 2>&1; then
  # macOS ships shasum instead of sha256sum
  ACTUAL_HASH="$(shasum -a 256 "${_TMPDIR}/${ASSET_NAME}" | awk '{print $1}')"
else
  error "sha256sum or shasum is required to verify checksums but was not found in PATH"
fi

if [[ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]]; then
  error "Checksum mismatch for ${ASSET_NAME}
  expected: ${EXPECTED_HASH}
  actual:   ${ACTUAL_HASH}"
fi
step "Checksum OK"

# ============================================================
# INSTALL
# ============================================================
_try_install() {
  # Attempt to install src -> dir/name. Returns non-zero on permission failure.
  local src="$1" dir="$2" name="$3"
  mkdir -p "$dir" 2>/dev/null || true
  if command -v install > /dev/null 2>&1; then
    install -m 0755 "$src" "${dir}/${name}"
  else
    # Fallback for minimal environments without install(1)
    cp "$src" "${dir}/${name}" && chmod 0755 "${dir}/${name}"
  fi
}

INSTALL_DIR=""

if [[ "$USER_INSTALL" == "true" ]]; then
  _user_dir="${HOME}/.local/bin"
  _try_install "${_TMPDIR}/${ASSET_NAME}" "$_user_dir" "$INSTALL_NAME" \
    || error "Failed to install to ${_user_dir}: check directory permissions"
  INSTALL_DIR="$_user_dir"
else
  _sys_dir="/usr/local/bin"
  if _try_install "${_TMPDIR}/${ASSET_NAME}" "$_sys_dir" "$INSTALL_NAME" 2>/dev/null; then
    INSTALL_DIR="$_sys_dir"
  else
    # Permission failure: check for interactive terminal
    if [[ -t 2 ]]; then
      printf "\n${_YELLOW}Insufficient permissions to install to %s.${_NC}\n\n" "$_sys_dir" >&2
      printf "  1) Retry with sudo\n" >&2
      printf "  2) Install to ~/.local/bin (no sudo required)\n" >&2
      printf "  3) Quit\n\n" >&2
      read -rp "Choose [1/2/3]: " _choice </dev/tty
      case "$_choice" in
        1)
          info "Retrying with sudo..."
          sudo install -m 0755 "${_TMPDIR}/${ASSET_NAME}" "${_sys_dir}/${INSTALL_NAME}" \
            || error "sudo install failed"
          INSTALL_DIR="$_sys_dir"
          ;;
        2)
          USER_INSTALL=true
          _user_dir="${HOME}/.local/bin"
          _try_install "${_TMPDIR}/${ASSET_NAME}" "$_user_dir" "$INSTALL_NAME" \
            || error "Failed to install to ${_user_dir}: check directory permissions"
          INSTALL_DIR="$_user_dir"
          ;;
        *)
          error "Installation aborted." ;;
      esac
    else
      # No TTY (e.g. curl | bash): print clear instructions and exit
      printf "\n${_RED}[ERROR]${_NC} Insufficient permissions to install to %s\n\n" "$_sys_dir" >&2
      printf "To retry as root:\n" >&2
      printf "  sudo bash <(curl -fsSL https://github.com/%s/releases/download/%s/install.sh)\n\n" \
        "$GITHUB_REPO" "$VERSION" >&2
      printf "To install without sudo (user install):\n" >&2
      printf "  curl -fsSL https://github.com/%s/releases/download/%s/install.sh | bash -s -- --user\n" \
        "$GITHUB_REPO" "$VERSION" >&2
      exit 1
    fi
  fi
fi

info "Installed ${INSTALL_NAME} to ${INSTALL_DIR}/${INSTALL_NAME}"

# ============================================================
# SHELL COMPLETIONS
# Included when enabled in .gpipe.yml.
# The binary is run once; output is captured and written in a single step.
# ============================================================
{{- if .Completions.Bash}}
if _bash_completion=$("${INSTALL_DIR}/${INSTALL_NAME}" completion bash 2>/dev/null); then
  if [[ "$USER_INSTALL" == "true" ]]; then
    mkdir -p "${HOME}/.bash_completion.d"
    printf '%s\n' "$_bash_completion" > "${HOME}/.bash_completion.d/${BINARY}"
    step "Bash completions → ~/.bash_completion.d/${BINARY}"
  elif printf '%s\n' "$_bash_completion" \
      | sudo install -m 0644 /dev/stdin "/etc/bash_completion.d/${BINARY}" 2>/dev/null; then
    step "Bash completions → /etc/bash_completion.d/${BINARY}"
  else
    mkdir -p "${HOME}/.bash_completion.d"
    printf '%s\n' "$_bash_completion" > "${HOME}/.bash_completion.d/${BINARY}"
    step "Bash completions → ~/.bash_completion.d/${BINARY}"
  fi
else
  warn "Bash completion not available from ${INSTALL_NAME}: binary may not support the completion subcommand"
fi
{{- end}}
{{- if .Completions.Zsh}}
if _zsh_completion=$("${INSTALL_DIR}/${INSTALL_NAME}" completion zsh 2>/dev/null); then
  if [[ "$USER_INSTALL" == "true" ]]; then
    mkdir -p "${HOME}/.zfunc"
    printf '%s\n' "$_zsh_completion" > "${HOME}/.zfunc/_${BINARY}"
    step "Zsh completions → ~/.zfunc/_${BINARY}"
  elif printf '%s\n' "$_zsh_completion" \
      | sudo install -m 0644 /dev/stdin "/usr/share/zsh/site-functions/_${BINARY}" 2>/dev/null; then
    step "Zsh completions → /usr/share/zsh/site-functions/_${BINARY}"
  else
    mkdir -p "${HOME}/.zfunc"
    printf '%s\n' "$_zsh_completion" > "${HOME}/.zfunc/_${BINARY}"
    step "Zsh completions → ~/.zfunc/_${BINARY}"
  fi
else
  warn "Zsh completion not available from ${INSTALL_NAME}: binary may not support the completion subcommand"
fi
{{- end}}
{{- if .Completions.Fish}}
if _fish_completion=$("${INSTALL_DIR}/${INSTALL_NAME}" completion fish 2>/dev/null); then
  if [[ "$USER_INSTALL" == "true" ]]; then
    mkdir -p "${HOME}/.config/fish/completions"
    printf '%s\n' "$_fish_completion" > "${HOME}/.config/fish/completions/${BINARY}.fish"
    step "Fish completions → ~/.config/fish/completions/${BINARY}.fish"
  elif printf '%s\n' "$_fish_completion" \
      | sudo install -m 0644 /dev/stdin "/usr/share/fish/completions/${BINARY}.fish" 2>/dev/null; then
    step "Fish completions → /usr/share/fish/completions/${BINARY}.fish"
  else
    mkdir -p "${HOME}/.config/fish/completions"
    printf '%s\n' "$_fish_completion" > "${HOME}/.config/fish/completions/${BINARY}.fish"
    step "Fish completions → ~/.config/fish/completions/${BINARY}.fish"
  fi
else
  warn "Fish completion not available from ${INSTALL_NAME}: binary may not support the completion subcommand"
fi
{{- end}}

{{- if .Hooks.PostSh}}
# ============================================================
# POST-INSTALL HOOK
# Injected from config at generation time.
# Available variables: GITHUB_REPO, VERSION, BINARY, INSTALL_NAME, INSTALL_DIR
# Note: hook runs in a subshell. set -euo pipefail is inherited.
# ============================================================
# --- gpipe: post-install hook ---
(
{{.Hooks.PostSh}}
)
# --- gpipe: end post-install hook ---
{{- end}}

# ============================================================
# PATH MANAGEMENT
# ============================================================
if [[ "$USER_INSTALL" == "true" ]]; then
  # $SHELL reflects the user's login shell. This is the best available
  # heuristic when running via curl | bash (no reliable current-shell detection).
  if ! printf ':%s:' "$PATH" | grep -qF ":${INSTALL_DIR}:"; then
    _export_line="export PATH=\"${INSTALL_DIR}:\$PATH\""
    _modified=()

    case "${SHELL:-}" in
      */zsh)
        for _f in "${ZDOTDIR:-$HOME}/.zshrc" "${ZDOTDIR:-$HOME}/.zprofile"; do
          if [[ -f "$_f" ]] && ! grep -qF "$INSTALL_DIR" "$_f" 2>/dev/null; then
            printf '\n# Added by %s installer\n%s\n' "$INSTALL_NAME" "$_export_line" >> "$_f"
            _modified+=("$_f")
          fi
        done ;;
      */fish)
        _fish_cfg="${HOME}/.config/fish/config.fish"
        mkdir -p "${HOME}/.config/fish"
        if ! grep -qF "$INSTALL_DIR" "$_fish_cfg" 2>/dev/null; then
          printf '\n# Added by %s installer\nfish_add_path %s\n' "$INSTALL_NAME" "$INSTALL_DIR" >> "$_fish_cfg"
          _modified+=("$_fish_cfg")
        fi ;;
      *)
        for _f in "${HOME}/.bashrc" "${HOME}/.bash_profile" "${HOME}/.profile"; do
          if [[ -f "$_f" ]] && ! grep -qF "$INSTALL_DIR" "$_f" 2>/dev/null; then
            printf '\n# Added by %s installer\n%s\n' "$INSTALL_NAME" "$_export_line" >> "$_f"
            _modified+=("$_f")
            break
          fi
        done ;;
    esac

    if [[ ${#_modified[@]} -gt 0 ]]; then
      warn "${INSTALL_DIR} was not in PATH: added to: ${_modified[*]}"
      warn "Restart your shell, or run now: ${_export_line}"
    else
      warn "${INSTALL_DIR} is not in PATH. Add the following to your shell profile:"
      warn "  ${_export_line}"
    fi
  fi
else
  if ! command -v "$INSTALL_NAME" > /dev/null 2>&1; then
    warn "${INSTALL_NAME} is not reachable via PATH"
    warn "  ${INSTALL_DIR} may need to be added to PATH manually"
  fi
fi

info "Successfully installed ${INSTALL_NAME} ${VERSION}"

} # end download guard
