#!/usr/bin/env bash

# Generated by gpipe - DO NOT EDIT MANUALLY!
# GitHub: https://github.com/thomaslaurenson/gpipe
# Release-Version: {{.Version}}
# Gpipe-Version: {{.GpipeVersion}}

# Re-generate with:
# gpipe generate --repo <owner/repo> --version <vX.Y.Z>

# Wrapping the script body in a brace block causes the shell to buffer the
# complete download before starting execution, preventing partial runs if the
# connection drops mid-pipe.
{
# set -euo pipefail is intentionally inside the brace block so it applies
# only after the download guard is established.
set -euo pipefail

# CONSTANTS: baked in at generation time
readonly GITHUB_REPO="{{.GithubRepo}}"
readonly VERSION="{{.Version}}"
readonly BINARY="{{.Binary}}"

# OUTPUT HELPERS
# Check stdout (fd 1) for colour support
if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]] && [[ "${TERM:-}" != "dumb" ]]; then
  _RED='\033[0;31m' _GREEN='\033[0;32m' _YELLOW='\033[1;33m'
  _CYAN='\033[0;36m' _BOLD='\033[1m' _NC='\033[0m'
else
  _RED='' _GREEN='' _YELLOW='' _CYAN='' _BOLD='' _NC=''
fi

# Every line of output carries a fixed-width [LEVEL] label, so output stays
# aligned and greppable and there is only one visual language to read.
#
# Each helper takes one or more messages. The first is the message proper;
# any further arguments are continuation lines, printed with the same label
# and a two-space indent so one multi-line message reads as a single block
# rather than as several unrelated ones.
#
# Arguments:
#   $1 - label, e.g. [INFO]
#   $2 - colour escape for the label
#   $3 - file descriptor to write to, 1 or 2
#   $4.. - message and any continuation lines
_log() {
  local label="$1" colour="$2" fd="$3"
  shift 3
  local is_first=1 arg line
  {
    for arg in "$@"; do
      # Arguments are split on newlines rather than printed as-is, so that
      # captured multi-line output from another command still comes out one
      # labelled line at a time instead of breaking the alignment.
      while IFS= read -r line; do
        if (( is_first )); then
          # %-7s pads the widest label ([ERROR]) to a fixed column, so the
          # text of every line starts at column 9 regardless of level.
          printf "%b%-7s%b %s\n" "${colour}" "${label}" "${_NC}" "${line}"
          is_first=0
        else
          printf "%b%-7s%b   %s\n" "${colour}" "${label}" "${_NC}" "${line}"
        fi
      done <<< "${arg}"
    done
  } >&"${fd}"
}

info()  { _log "[INFO]"  "${_CYAN}"   1 "$@"; }
ok()    { _log "[OK]"    "${_GREEN}"  1 "$@"; }
warn()  { _log "[WARN]"  "${_YELLOW}" 2 "$@"; }
error() { _log "[ERROR]" "${_RED}"    2 "$@"; exit 1; }

# Print help message to stdout.
show_help() {
  cat <<EOF
${_BOLD}${BINARY} installer${_NC}

USAGE:
  bash install.sh [OPTIONS]

OPTIONS:
  -h, --help      Show this help message
  --user          Install to ~/.local/bin (no sudo required)
  --system        Install to /usr/local/bin (default, may require sudo)
  --no-verify     Skip cosign signature verification on checksums.txt
                  By default, the installer verifies the release signature
                  using cosign. Use this flag only if cosign is unavailable.
                  Install cosign:
                  https://docs.sigstore.dev/cosign/system_config/installation/

EXAMPLES:
  # System-wide install (default)
  curl -fsSL \
    https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh \
    | bash

  # User-local install, no sudo needed
  curl -fsSL \
    https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh \
    | bash -s -- --user

  # Skip cosign verification (not recommended)
  curl -fsSL \
    https://github.com/${GITHUB_REPO}/releases/download/${VERSION}/install.sh \
    | bash -s -- --no-verify
EOF
}

# Parse command-line arguments and set USER_INSTALL and NO_VERIFY.
#
# Arguments:
#   $@ - command-line arguments
# Environment:
#   USER_INSTALL - set to true for --user, false for --system
#   NO_VERIFY    - set to true when --no-verify is passed
# Returns:
#   0 on success
#   exits 1 for unknown options
parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)    show_help; exit 0 ;;
      --user)       USER_INSTALL=true;  shift ;;
      --system)     USER_INSTALL=false; shift ;;
      --no-verify)  NO_VERIFY=true;     shift ;;
      *)            error "Unknown option: $1. Run with --help for usage." ;;
    esac
  done
}

# Detect the current OS and architecture and print a platform identifier.
#
# Outputs:
#   stdout: platform string, e.g. linux_amd64 or darwin_arm64
# Returns:
#   0 on success
#   exits 1 for unsupported OS or architecture
detect_platform() {
  local os arch
  local _os _arch
  _os="$(uname -s)"
  _arch="$(uname -m)"

  case "$_os" in
    Linux)  os="linux"  ;;
    Darwin) os="darwin" ;;
    *)      error "Unsupported operating system: ${_os}" ;;
  esac

  case "$_arch" in
    x86_64)        arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *)             error "Unsupported architecture: ${_arch}" ;;
  esac

  printf '%s_%s' "$os" "$arch"
}

# Resolve the release asset filename for a given platform identifier.
#
# Arguments:
#   $1 - platform string, e.g. linux_amd64
# Outputs:
#   stdout: asset filename, e.g. mytool_linux_amd64
# Returns:
#   0 on success
#   exits 1 for unsupported platform
resolve_asset() {
  local platform="$1"
  case "$platform" in
{{- range .ShPlatforms}}
    {{.ID}}) printf '%s' "{{.AssetName}}" ;;
{{- end}}
    *)
      local supported
      supported="$(printf '%s ' '{{range .ShPlatforms}}{{.ID}} {{end}}')"
      error "Unsupported platform: ${platform}. Supported: ${supported}"
      ;;
  esac
}

# Initialise the _download function, preferring curl over wget.
#
# Defines _download as a function in the current shell. Exits with an error
# if neither curl nor wget is available.
#
# Returns:
#   0 on success
#   exits 1 if neither curl nor wget is found
setup_downloader() {
  if command -v curl > /dev/null 2>&1; then
    _fetch() {
      curl -fsSL --retry 3 --connect-timeout 30 --speed-limit 1024 --speed-time 30 "$1" -o "$2"
    }
  elif command -v wget > /dev/null 2>&1; then
    _fetch() {
      # -nv (not -q) keeps the diagnostics _download replays on failure. It is
      # a two-character option, so unlike -qO it cannot be bundled with -O.
      wget --tries=3 --connect-timeout=30 --timeout=30 -nv -O "$2" "$1"
    }
  else
    error "curl or wget is required to download files"
  fi
}

# Download a single URL to a destination path.
#
# curl and wget each report in their own format, which would otherwise be the
# only output in the run not wearing a [LEVEL] label. Their output is captured
# and replayed only when the download fails, so a successful run stays uniform
# without losing the diagnostics that matter when one does not.
#
# Arguments:
#   $1 - URL to download
#   $2 - destination file path
# Returns:
#   0 on success
#   exits 1 if the download fails
_download() {
  local url="$1" dest="$2" out
  if ! out="$(_fetch "${url}" "${dest}" 2>&1)"; then
    if [[ -n "${out}" ]]; then
      error "Failed to download ${url}" "${out}"
    fi
    error "Failed to download ${url}"
  fi
}

# Download the binary, checksums, and cosign bundle into a temp directory.
#
# Arguments:
#   $1 - destination directory (must already exist)
#   $2 - asset filename
# Environment:
#   GITHUB_REPO, VERSION - used to construct download URLs
# Returns:
#   0 on success
#   exits 1 if any download fails
download_assets() {
  local dest_dir="$1"
  local asset_name="$2"
  local base_url
  base_url="https://github.com/${GITHUB_REPO}/releases/download/${VERSION}"
  local download_url="${base_url}/${asset_name}"
  local checksums_url="${base_url}/checksums.txt"
  local checksums_sig_url="${base_url}/checksums.txt.sigstore.json"

  info "Downloading ${BINARY} ${VERSION} for ${PLATFORM}" "${download_url}"
  _download "${download_url}"       "${dest_dir}/${asset_name}"
  _download "${checksums_url}"      "${dest_dir}/checksums.txt"
  _download "${checksums_sig_url}"  "${dest_dir}/checksums.txt.sigstore.json"
}

# Verify the cosign signature on checksums.txt.
#
# Skips verification when NO_VERIFY is true. Exits with an error if cosign
# is not found and NO_VERIFY is false. The certificate identity regexp
# (bound to this repo and this version's tag ref) is baked in as a literal
# at generation time; see cosignCertIdentity in generator.go.
#
# Arguments:
#   $1 - directory containing checksums.txt and checksums.txt.sigstore.json
# Environment:
#   NO_VERIFY - skip when true
# Returns:
#   0 on success or when skipped
#   exits 1 if cosign is missing or verification fails
verify_signature() {
  local dir="$1"

  if [[ "${NO_VERIFY}" == "true" ]]; then
    warn "Skipping cosign signature verification (--no-verify passed)" \
         "The checksum check that still runs only detects accidental" \
         "corruption: checksums.txt comes from the same origin as the" \
         "binary, so it offers no protection against a tampered release."
    return 0
  fi

  if ! command -v cosign > /dev/null 2>&1; then
    error "cosign not found in PATH" \
          "The installer verifies release signatures by default to ensure" \
          "the download has not been tampered with. cosign is required for this." \
          "Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/" \
          "To skip verification (not recommended) pass following arguments:" \
          "  bash -s -- --no-verify"
  fi

  info "Verifying cosign signature on checksums.txt"
  local cert_identity
  # Anchored (^...$) to this repository and to a workflow run triggered by
  # pushing this exact version tag (see cosignCertIdentity in generator.go
  # for the full rationale). The workflow filename segment is left open
  # (.+) since it is not known at generation time.
  cert_identity="{{.CosignCertIdentity}}"
  # cosign writes its own progress and its "Verified OK" confirmation to
  # stderr. Captured rather than passed through, so a successful run reports
  # the result in gpipe's own format; on failure the captured text is
  # replayed under the [ERROR] label, where it is the useful diagnostic.
  local cosign_out
  if ! cosign_out="$(cosign verify-blob \
    --bundle "${dir}/checksums.txt.sigstore.json" \
    --certificate-identity-regexp="${cert_identity}" \
    --certificate-oidc-issuer="https://token.actions.githubusercontent.com" \
    "${dir}/checksums.txt" 2>&1)"; then
    if [[ -n "${cosign_out}" ]]; then
      error "cosign signature verification failed" "${cosign_out}"
    fi
    error "cosign signature verification failed"
  fi
  ok "Cosign signature verified"
}

# Verify the SHA-256 checksum of a downloaded asset.
#
# Arguments:
#   $1 - directory containing both the asset and checksums.txt
#   $2 - asset filename to verify
# Returns:
#   0 when the checksum matches
#   exits 1 if sha256sum/shasum is missing, the entry is not found, or the
#   hash does not match
verify_checksum() {
  local dir="$1"
  local asset_name="$2"
  local expected_hash actual_hash

  info "Verifying checksum"

  # Match the filename field ($2) exactly rather than doing a substring grep.
  # A substring match means one asset name that is a prefix of another (e.g.
  # "tool-linux-x86_64" and "tool-linux-x86_64-musl") matches multiple lines,
  # yielding several hashes and a false "checksum mismatch" on a valid install.
  expected_hash="$(awk -v name="${asset_name}" '$2 == name {print $1}' "${dir}/checksums.txt")"
  if [[ -z "${expected_hash}" ]]; then
    error "Checksum not found for ${asset_name} in checksums.txt"
  fi

  if command -v sha256sum > /dev/null 2>&1; then
    actual_hash="$(sha256sum "${dir}/${asset_name}" | awk '{print $1}')"
  elif command -v shasum > /dev/null 2>&1; then
    actual_hash="$(shasum -a 256 "${dir}/${asset_name}" | awk '{print $1}')"
  else
    error "sha256sum or shasum is required to verify checksums but was not found in PATH"
  fi

  if [[ "${expected_hash}" != "${actual_hash}" ]]; then
    error "Checksum mismatch for ${asset_name}" \
          "expected: ${expected_hash}" \
          "actual:   ${actual_hash}"
  fi
  ok "Checksum verified"
}

# Attempt to install a binary to a directory.
#
# Uses install(1) when available, falling back to cp + chmod for minimal
# environments. Returns non-zero on permission failure without exiting, so
# the caller can handle the fallback.
#
# Arguments:
#   $1 - source file path
#   $2 - destination directory
#   $3 - destination filename
# Returns:
#   0 on success
#   non-zero on failure (permission denied or install error)
_try_install() {
  local src="$1" dir="$2" name="$3"
  mkdir -p "$dir" 2>/dev/null || true
  if command -v install > /dev/null 2>&1; then
    install -m 0755 "$src" "${dir}/${name}"
  else
    cp "$src" "${dir}/${name}" && chmod 0755 "${dir}/${name}"
  fi
}

# Install the binary to the resolved install directory.
#
# For system installs, falls back to a sudo prompt when permissions are
# insufficient. In non-interactive (no TTY) mode, prints instructions and
# exits rather than prompting.
#
# Arguments:
#   $1 - source file path (downloaded binary in tmp dir)
# Environment:
#   USER_INSTALL  - true for user install, false for system install
#   BINARY        - destination filename
#   INSTALL_DIR   - set by this function to the chosen install path
#   GITHUB_REPO, VERSION - used in no-TTY error messages
# Returns:
#   0 on success
#   exits 1 on failure
install_binary() {
  local src="$1"

  if [[ "${USER_INSTALL}" == "true" ]]; then
    local user_dir="${HOME}/.local/bin"
    _try_install "${src}" "${user_dir}" "${BINARY}" \
      || error "Failed to install to ${user_dir}: check directory permissions"
    INSTALL_DIR="${user_dir}"
  else
    local sys_dir="/usr/local/bin"
    local try_err
    if try_err="$(_try_install "${src}" "${sys_dir}" "${BINARY}" 2>&1)"; then
      INSTALL_DIR="${sys_dir}"
    else
      if [[ -t 2 ]]; then
        if [[ -n "${try_err}" ]]; then
          warn "Insufficient permissions to install to ${sys_dir}" "${try_err}"
        else
          warn "Insufficient permissions to install to ${sys_dir}"
        fi
        # The menu and its prompt are interactive UI rather than log output,
        # so they are the one place that stays unlabelled: prefixing the
        # choices with [WARN] would read as four more warnings.
        printf "\n  1) Retry with sudo\n" >&2
        printf "  2) Install to ~/.local/bin (no sudo required)\n" >&2
        printf "  3) Quit\n\n" >&2
        read -rp "Choose [1/2/3]: " _choice </dev/tty
        case "${_choice}" in
          1)
            info "Retrying with sudo"
            # sys_dir may not exist yet (e.g. a fresh macOS install): install(1)
            # does not create its destination directory, so it must exist first.
            sudo mkdir -p "${sys_dir}" \
              || error "sudo mkdir failed for ${sys_dir}"
            sudo install -m 0755 "${src}" "${sys_dir}/${BINARY}" \
              || error "sudo install failed"
            INSTALL_DIR="${sys_dir}"
            ;;
          2)
            USER_INSTALL=true
            local user_dir="${HOME}/.local/bin"
            _try_install "${src}" "${user_dir}" "${BINARY}" \
              || error "Failed to install to ${user_dir}: check directory permissions"
            INSTALL_DIR="${user_dir}"
            ;;
          *)
            error "Installation aborted" ;;
        esac
      else
        local install_url
        install_url="https://github.com/${GITHUB_REPO}"
        install_url+="/releases/download/${VERSION}/install.sh"
        error "Insufficient permissions to install to ${sys_dir}" \
              "To retry as root:" \
              "  sudo bash <(curl -fsSL ${install_url})" \
              "To install without sudo (user install):" \
              "  curl -fsSL ${install_url} | bash -s -- --user"
      fi
    fi
  fi

  ok "Installed ${BINARY} to ${INSTALL_DIR}/${BINARY}"
}


# Report whether the installed binary is actually reachable via PATH.
#
# Reports only. Nothing is written to any shell profile: which file a given
# user's shell reads is a guess a curl | bash pipeline cannot make reliably,
# and a wrong guess edits a dotfile the user never asked the installer to
# touch. The exact line to add is printed instead.
#
# Environment:
#   INSTALL_DIR, BINARY, USER_INSTALL, PATH - read
# Returns:
#   0 always
manage_path() {
  local resolved
  resolved="$(command -v "${BINARY}" 2>/dev/null || true)"

  if [[ "${resolved}" == "${INSTALL_DIR}/${BINARY}" ]]; then
    return 0
  fi

  if [[ -n "${resolved}" ]]; then
    # A different binary of the same name earlier in PATH shadows the one just
    # installed, so `command -v` succeeding is not sufficient.
    warn "${BINARY} on PATH resolves to ${resolved}, not ${INSTALL_DIR}/${BINARY}" \
         "${INSTALL_DIR} may need to come earlier in PATH"
    return 0
  fi

  warn "${INSTALL_DIR} is not in PATH. Add the following to your shell profile:" \
       "export PATH=\"${INSTALL_DIR}:\$PATH\""
}


# Entry point: parse args, detect platform, download, verify, and install.
#
# Arguments:
#   $@ - command-line arguments forwarded from the shell invocation
# Returns:
#   0 on success
#   exits 1 on any failure
main() {
  USER_INSTALL=false
  NO_VERIFY=false
  INSTALL_DIR=""
  PLATFORM=""

  parse_args "$@"

  PLATFORM="$(detect_platform)"
  local asset_name
  asset_name="$(resolve_asset "${PLATFORM}")"

  setup_downloader

  local tmp_dir
  tmp_dir="$(mktemp -d)"
  # Double-quoted so tmp_dir expands now (at trap-set time), not at EXIT.
  # A local variable is gone by the time EXIT fires after main returns.
  # shellcheck disable=SC2064
  trap "rm -rf '${tmp_dir}'" EXIT

{{- if .Hooks.PreSh}}
  # gpipe test: pre-install-hook
  # Pre-install hook injected from config at generation time.
  # Available variables: GITHUB_REPO, VERSION, BINARY
  (
{{.Hooks.PreSh}}
  )
{{- end}}

  download_assets "${tmp_dir}" "${asset_name}"
  verify_signature "${tmp_dir}"
  verify_checksum "${tmp_dir}" "${asset_name}"
  install_binary "${tmp_dir}/${asset_name}"

{{- if .Hooks.PostSh}}
  # gpipe test: post-install-hook
  # Post-install hook injected from config at generation time.
  # Available variables: GITHUB_REPO, VERSION, BINARY, INSTALL_DIR
  (
{{.Hooks.PostSh}}
  )
{{- end}}

  manage_path

  ok "Successfully installed ${BINARY} ${VERSION}"
}

# Guard: run main when executed directly or piped (curl|bash), but not when
# sourced for testing. BASH_SOURCE[0] is unset when piped, so -z catches that.
if [[ -z "${BASH_SOURCE[0]:-}" || "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi

} # end download guard
