# Generated by gpipe - DO NOT EDIT MANUALLY!
# GitHub: https://github.com/thomaslaurenson/gpipe
# Version: {{.Version}}

# Re-generate with:
# gpipe generate --repo <owner/repo> --version <vX.Y.Z>

#Requires -Version 5.1

[CmdletBinding()]
param(
    [switch]$User,
    [switch]$Help,
    [switch]$NoVerify
)

$ErrorActionPreference = 'Stop'
$ProgressPreference    = 'SilentlyContinue'

# Windows PowerShell 5.1 (Desktop edition) can default to TLS 1.0/1.1 on older
# Windows builds, which GitHub rejects. PowerShell 7+ (Core) already defaults
# to modern TLS, so this is scoped to Desktop to avoid touching Core's default.
if ($PSVersionTable.PSEdition -eq 'Desktop') {
    [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
}

# CONSTANTS: baked in at generation time
$script:GithubRepo  = '{{.GithubRepo}}'
$script:Version     = '{{.Version}}'
$script:Binary      = '{{.Binary}}'
$script:InstallName = '{{.InstallName}}'
# Avoids emitting "name.exe.exe" when install-name is already configured with
# a trailing .exe.
$script:InstallExeName = if ($script:InstallName -like '*.exe') { $script:InstallName } else { "$script:InstallName.exe" }

# OUTPUT HELPERS
# Check for colour support via NO_COLOR environment variable
$script:NoColor = ($null -ne $env:NO_COLOR)

# Print one or more messages under a fixed-width [LEVEL] label.
#
# Every line of output carries a label, so output stays aligned and greppable
# and there is only one visual language to read. The first message is the
# message proper; any further ones are continuation lines, printed with the
# same label and a two-space indent so a multi-line message reads as a single
# block rather than as several unrelated ones. Messages containing newlines
# are split, so captured output from another command still comes out one
# labelled line at a time instead of breaking the alignment.
#
# Parameters:
#   Label  - level label, e.g. [INFO]
#   Colour - ConsoleColor name for the label
#   Msg    - message and any continuation lines
function Write-Label {
    param(
        [string]$Label,
        [string]$Colour,
        [string[]]$Msg
    )

    # PadRight(7) pads the widest label ([ERROR]) to a fixed column, so the
    # text of every line starts at column 9 regardless of level.
    $padded = $Label.PadRight(7)
    $isFirst = $true
    foreach ($entry in $Msg) {
        foreach ($line in ($entry -split "`r?`n")) {
            $indent = if ($isFirst) { ' ' } else { '   ' }
            if ($script:NoColor) {
                Write-Host "$padded$indent$line"
            } else {
                Write-Host $padded -ForegroundColor $Colour -NoNewline
                Write-Host "$indent$line"
            }
            $isFirst = $false
        }
    }
}

# Print an informational message under a cyan [INFO] label.
#
# Parameters:
#   Msg - message and any continuation lines
function Write-Info {
    param([string[]]$Msg)
    Write-Label -Label '[INFO]' -Colour Cyan -Msg $Msg
}

# Print a success message under a green [OK] label.
#
# Parameters:
#   Msg - message and any continuation lines
function Write-Ok {
    param([string[]]$Msg)
    Write-Label -Label '[OK]' -Colour Green -Msg $Msg
}

# Print a warning under a yellow [WARN] label.
#
# Parameters:
#   Msg - message and any continuation lines
function Write-Warn {
    param([string[]]$Msg)
    Write-Label -Label '[WARN]' -Colour Yellow -Msg $Msg
}

# Print an error under a red [ERROR] label and abort.
#
# Parameters:
#   Msg - message and any continuation lines
function Exit-Error {
    param([string[]]$Msg)
    Write-Label -Label '[ERROR]' -Colour Red -Msg $Msg
    throw ($Msg -join ' ')
}

# Print help and usage information to stdout
function Show-Help {
    Write-Host @"
$script:InstallName installer

USAGE:
  .\install.ps1 [-User] [-NoVerify] [-Help]

OPTIONS:
  -User       Install to user directory (no elevation required)
              Default path: $env:LOCALAPPDATA\Programs\$script:InstallName
  -NoVerify   Skip cosign signature verification on checksums.txt
              By default, the installer verifies the release signature
              using cosign. Use this flag only if cosign is unavailable.
              Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/
  -Help       Show this help message

EXAMPLES:
  # System-wide install (default, prompts for elevation if not Administrator)
  .\install.ps1

  # User install, no elevation needed
  .\install.ps1 -User

  # Skip cosign verification (not recommended)
  .\install.ps1 -NoVerify

  # Piped user install
  Invoke-WebRequest -Uri "https://github.com/$script:GithubRepo/releases/download/$script:Version/install.ps1" ``
    -OutFile install.ps1; .\install.ps1 -User

"@
}

# Detect the current Windows architecture and return a platform identifier.
#
# Reads PROCESSOR_ARCHITEW6432 first to correctly handle 32-bit processes
# running under WOW64 on a 64-bit OS. Falls back to PROCESSOR_ARCHITECTURE.
#
# Outputs:
#   string: platform identifier, e.g. windows_amd64 or windows_arm64
# Throws:
#   terminating error for unsupported architectures
function Get-Platform {
    $osArch = $env:PROCESSOR_ARCHITECTURE
    if ($env:PROCESSOR_ARCHITEW6432) { $osArch = $env:PROCESSOR_ARCHITEW6432 }

    $normArch = switch ($osArch) {
        'AMD64' { 'amd64' }
        'ARM64' { 'arm64' }
        default { Exit-Error "Unsupported architecture: $osArch" }
    }

    return "windows_$normArch"
}

# Resolve the release asset filename for a given platform identifier.
#
# Parameters:
#   Platform - platform string, e.g. windows_amd64
# Outputs:
#   string: asset filename, e.g. mytool_windows_amd64.exe
# Throws:
#   terminating error for unsupported platforms
function Resolve-Asset {
    param([string]$Platform)

    # Ps1Platforms is pre-filtered to windows_* by the generator, so no
    # runtime filtering of $assetNames.Keys is needed below.
    $assetNames = @{
{{- range .Ps1Platforms}}
        '{{.ID}}' = '{{.AssetName}}'
{{- end}}
    }

    if (-not $assetNames.ContainsKey($Platform)) {
        $supported = $assetNames.Keys -join ', '
        Exit-Error "Unsupported platform: $Platform. Supported: $supported"
    }

    return $assetNames[$Platform]
}

# Download the binary, checksums, and cosign bundle into a directory.
#
# Parameters:
#   TmpDir    - destination directory (must already exist)
#   AssetName - filename of the release binary asset
# Globals read:
#   $script:GithubRepo, $script:Version, $script:Binary
# Throws:
#   terminating error if any download fails
function Invoke-DownloadAsset {
    param(
        [string]$TmpDir,
        [string]$AssetName
    )

    $downloadUrl     = "https://github.com/$script:GithubRepo/releases/download/$script:Version/$AssetName"
    $checksumsUrl    = "https://github.com/$script:GithubRepo/releases/download/$script:Version/checksums.txt"
    $checksumsSigUrl = "https://github.com/$script:GithubRepo/releases/download/$script:Version/checksums.txt.sigstore.json"

    Write-Info "Downloading $script:Binary $script:Version for $(Get-Platform)", $downloadUrl

    try {
        Invoke-WebRequest -Uri $downloadUrl -OutFile "$TmpDir\$AssetName" -UseBasicParsing -TimeoutSec 60
    } catch {
        Exit-Error "Failed to download ${AssetName}: $_"
    }

    try {
        Invoke-WebRequest -Uri $checksumsUrl -OutFile "$TmpDir\checksums.txt" -UseBasicParsing -TimeoutSec 30
    } catch {
        Exit-Error "Failed to download checksums.txt: $_"
    }

    try {
        Invoke-WebRequest -Uri $checksumsSigUrl -OutFile "$TmpDir\checksums.txt.sigstore.json" -UseBasicParsing -TimeoutSec 30
    } catch {
        Exit-Error "Failed to download checksums.txt.sigstore.json: $_"
    }
}

# Thin wrapper around the cosign native command; exists so tests can mock it.
function Invoke-Cosign {
    & cosign @args
}

# Verify the cosign signature on checksums.txt.
#
# Skips verification when $NoVerify is true. Exits with an error if cosign
# is not found and $NoVerify is false. The certificate identity regexp
# (bound to this repo and this version's tag ref) is baked in as a literal
# at generation time; see cosignCertIdentity in generator.go.
#
# Parameters:
#   TmpDir   - directory containing checksums.txt and checksums.txt.sigstore.json
#   NoVerify - when true, skip verification and emit a warning
# Throws:
#   terminating error if cosign is missing or verification fails
function Confirm-Signature {
    param(
        [string]$TmpDir,
        [bool]$NoVerify
    )

    if ($NoVerify) {
        Write-Warn 'Skipping cosign signature verification (-NoVerify passed)',
                   'The checksum check that still runs only detects accidental',
                   'corruption: checksums.txt comes from the same origin as the',
                   'binary, so it offers no protection against a tampered release.'
        return
    }

    if (-not (Get-Command cosign -ErrorAction SilentlyContinue)) {
        Exit-Error @'
cosign not found in PATH.

  The installer verifies release signatures by default to ensure
  the download has not been tampered with. cosign is required for this.

  Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/

  To skip verification (not recommended):
    .\install.ps1 -NoVerify
'@
    }

    Write-Info 'Verifying cosign signature on checksums.txt'
    # Anchored (^...$) to this repository and to a workflow run triggered by
    # pushing this exact version tag (see cosignCertIdentity in generator.go
    # for the full rationale).
    #
    # cosign writes its own progress and its "Verified OK" confirmation to
    # stderr. Captured rather than passed through, so a successful run reports
    # the result in gpipe's own format; on failure the captured text is
    # replayed under the [ERROR] label, where it is the useful diagnostic.
    # 2>&1 merges stderr into the pipeline as ErrorRecord objects, so each is
    # cast to a string before being handed to the output helpers.
    #
    # ErrorActionPreference drops to Continue for the duration of the call:
    # under 'Stop', some PowerShell versions treat a native command's stderr
    # as a terminating error, which would abort the install on cosign's
    # ordinary progress chatter rather than on a real failure. Restored in a
    # finally rather than scoped by wrapping the call in a child scriptblock,
    # because PSScriptAnalyzer's PSReviewUnusedParameter does not count
    # parameter usage inside a nested scriptblock and reports $TmpDir unused.
    $prevErrorAction = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        $cosignOut = Invoke-Cosign verify-blob `
            --bundle "$TmpDir\checksums.txt.sigstore.json" `
            --certificate-identity-regexp='{{.CosignCertIdentity}}' `
            --certificate-oidc-issuer='https://token.actions.githubusercontent.com' `
            "$TmpDir\checksums.txt" 2>&1
    } finally {
        $ErrorActionPreference = $prevErrorAction
    }
    if ($LASTEXITCODE -ne 0) {
        # Where-Object first: piping a $null $cosignOut still sends one item
        # down the pipeline, and calling .ToString() on it would throw.
        $detail = @($cosignOut | Where-Object { $null -ne $_ } | ForEach-Object { $_.ToString() })
        if ($detail.Count -gt 0) {
            Exit-Error (@('cosign signature verification failed') + $detail)
        }
        Exit-Error 'cosign signature verification failed'
    }
    Write-Ok 'Cosign signature verified'
}

# Verify the SHA-256 checksum of a downloaded asset against checksums.txt.
#
# Parameters:
#   TmpDir    - directory containing both the asset and checksums.txt
#   AssetName - filename of the asset to verify
# Throws:
#   terminating error if the entry is not found or hashes do not match
function Confirm-Checksum {
    param(
        [string]$TmpDir,
        [string]$AssetName
    )

    Write-Info 'Verifying checksum'

    $checksumLine = Get-Content "$TmpDir\checksums.txt" |
        Where-Object { $_ -like "*  $AssetName" }

    if (-not $checksumLine) {
        Exit-Error "Checksum not found for $AssetName in checksums.txt"
    }

    $expectedHash = ($checksumLine -split '\s+')[0].ToLower()
    $actualHash   = (Get-FileHash -Algorithm SHA256 "$TmpDir\$AssetName").Hash.ToLower()

    if ($expectedHash -ne $actualHash) {
        Exit-Error "Checksum mismatch for $AssetName", "expected: $expectedHash", "actual:   $actualHash"
    }

    Write-Ok 'Checksum verified'
}

# Resolve the installation directory based on install type and privileges.
#
# For system installs without Administrator rights, offers an interactive
# prompt (when a TTY is available) or prints instructions and exits.
#
# Parameters:
#   UserInstall - when true, resolve a user-local path without elevation
#   NoVerify    - forwarded to the elevated relaunch so -NoVerify is not lost
# Outputs:
#   PSCustomObject with:
#     Path          - resolved absolute install directory path
#     IsUserInstall - true if this resolved to a user-local path, even when
#                     -UserInstall was not originally requested (the
#                     no-elevation fallback below downgrades to a user
#                     install, and callers must use the User PATH scope,
#                     not Machine, for that case)
# Globals read:
#   $script:InstallName, $script:GithubRepo, $script:Version
function Resolve-InstallDir {
    param(
        [bool]$UserInstall,
        [bool]$NoVerify
    )

    $userDir = Join-Path $env:LOCALAPPDATA "Programs\$script:InstallName"

    if ($UserInstall) {
        return [PSCustomObject]@{ Path = $userDir; IsUserInstall = $true }
    }

    $systemDir = "$env:ProgramFiles\$script:InstallName"
    $isAdmin   = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
                    [Security.Principal.WindowsBuiltInRole]::Administrator)

    if ($isAdmin) {
        return [PSCustomObject]@{ Path = $systemDir; IsUserInstall = $false }
    }

    # [Environment]::UserInteractive is true in CI runners and any session
    # with redirected stdin (it is only false for Windows services), so it
    # is combined with an explicit redirected-input check before prompting.
    if ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected) {
        Write-Warn "Insufficient permissions to install to $systemDir"
        # The menu and its prompt are interactive UI rather than log output,
        # so they are the one place that stays unlabelled: prefixing the
        # choices with [WARN] would read as three more warnings.
        Write-Host ''
        Write-Host '  1) Re-run as Administrator (opens elevated prompt)'
        Write-Host "  2) Install to $userDir (no elevation)"
        Write-Host '  3) Quit'
        Write-Host ''
        $choice = Read-Host 'Choose [1/2/3]'

        switch ($choice.Trim()) {
            '1' {
                if (-not [string]::IsNullOrEmpty($PSCommandPath)) {
                    Write-Info 'Launching elevated session'
                    # Use the same PowerShell edition that is currently running:
                    # pwsh for PowerShell 7+ (Core), powershell for Windows PS 5.1.
                    $psExe    = if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' }
                    $extraArg = if ($NoVerify) { ' -NoVerify' } else { '' }
                    $argList  = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`"$extraArg"
                    Start-Process $psExe -Verb RunAs -ArgumentList $argList -Wait
                    exit 0
                } else {
                    # $PSCommandPath is empty when the script was piped or dot-sourced.
                    # The user already has install.ps1 on disk from the Invoke-WebRequest
                    # step, so direct them to run it from an elevated prompt.
                    $psExe = if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' }
                    Exit-Error 'Cannot auto-elevate from a piped session. Run from an elevated prompt:', "  $psExe -File .\install.ps1"
                }
            }
            '2' {
                return [PSCustomObject]@{ Path = $userDir; IsUserInstall = $true }
            }
            default { Exit-Error 'Installation aborted' }
        }
    } else {
        $psExe = if ($PSVersionTable.PSEdition -eq 'Core') { 'pwsh' } else { 'powershell' }
        $downloadCmd = "  Invoke-WebRequest -Uri `"https://github.com/$script:GithubRepo/releases/download/$script:Version/install.ps1`" -OutFile install.ps1"
        Exit-Error "Insufficient permissions to install to $systemDir", `
                   'To install in an elevated PowerShell session, download and run:', `
                   $downloadCmd, `
                   "  Start-Process $psExe -Verb RunAs -ArgumentList `"-File .\install.ps1`" -Wait", `
                   'To install without elevation (user install):', `
                   $downloadCmd, `
                   '  .\install.ps1 -User'
    }
}

# Copy the downloaded binary to the install directory.
#
# Parameters:
#   TmpDir     - directory containing the downloaded asset
#   AssetName  - filename of the asset to install
#   InstallDir - destination directory (created if absent)
# Globals read:
#   $script:InstallName
function Install-Binary {
    param(
        [string]$TmpDir,
        [string]$AssetName,
        [string]$InstallDir
    )

    if (-not (Test-Path $InstallDir)) {
        New-Item -ItemType Directory -Path $InstallDir | Out-Null
    }

    Copy-Item "$TmpDir\$AssetName" "$InstallDir\$script:InstallExeName" -Force
    Write-Ok "Installed $script:InstallName to $InstallDir\$script:InstallExeName"
}

{{- if .Completions.PowerShell}}
# gpipe test: powershell-completions

# Install PowerShell completions generated by the installed binary.
#
# Appends a guarded completion block to $PROFILE. Idempotent: skips if the
# marker comment is already present. Warns rather than failing if the binary
# does not support the completion subcommand.
#
# Parameters:
#   InstallDir - directory containing the installed binary
# Globals read:
#   $script:InstallName, $script:Binary
function Install-Completion {
    param([string]$InstallDir)

    try {
        $completionOutput = & "$InstallDir\$script:InstallExeName" completion powershell 2>&1
    } catch {
        Write-Warn "PowerShell completion generation failed, skipping: $_"
        return
    }

    if ($LASTEXITCODE -ne 0) {
        Write-Warn "PowerShell completion not available from $script:InstallName`: binary may not support the completion subcommand"
        return
    }

    $profileDir = Split-Path $PROFILE
    if (-not (Test-Path $profileDir)) { New-Item -ItemType Directory -Path $profileDir | Out-Null }
    if (-not (Test-Path $PROFILE))    { New-Item -ItemType File      -Path $PROFILE    | Out-Null }

    $marker  = "# $script:Binary completions (added by gpipe)"
    $content = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
    if (-not $content -or $content -notmatch [regex]::Escape($marker)) {
        Add-Content -Path $PROFILE -Value "`n$marker`n$completionOutput"
        Write-Ok "PowerShell completions -> $PROFILE"
    }
}
{{- end}}

# Ensure InstallDir is present in PATH.
#
# For user installs, persists to the User PATH registry key.
# For system installs, persists to the Machine PATH registry key (requires
# Administrator rights, which a system install already has) and also updates
# the current session so the binary is immediately available.
#
# Parameters:
#   InstallDir  - directory that was installed to
#   UserInstall - true when this was a user-local install
# Globals read:
#   $script:InstallName
function Update-Path {
    param(
        [string]$InstallDir,
        [bool]$UserInstall
    )

    # User installs persist to the 'User' PATH; system installs persist to the
    # 'Machine' PATH (a system install already requires Administrator rights,
    # so the Machine write will not fail with access denied).
    $scope = if ($UserInstall) { 'User' } else { 'Machine' }
    $label = if ($UserInstall) { 'user' } else { 'system' }

    $persisted = [Environment]::GetEnvironmentVariable('PATH', $scope)

    # Split on ';' and compare each entry exactly rather than using a substring
    # match: a substring check treats 'C:\foo\bar' as already present when the
    # PATH only contains 'C:\foo\barbaz'.
    $persistedParts = @($persisted -split ';' | Where-Object { $_ -ne '' })
    if ($persistedParts -notcontains $InstallDir) {
        $newPersisted = (@($InstallDir) + $persistedParts) -join ';'
        [Environment]::SetEnvironmentVariable('PATH', $newPersisted, $scope)
        Write-Warn "Added $InstallDir to $label PATH. Restart your terminal for the change to take effect."
    }

    # Update the current session immediately, with the same exact-entry check.
    $sessionParts = @($env:PATH -split ';' | Where-Object { $_ -ne '' })
    if ($sessionParts -notcontains $InstallDir) {
        $env:PATH = (@($InstallDir) + $sessionParts) -join ';'
    }
}

function Invoke-Installer {
    param(
        [switch]$User,
        [switch]$Help,
        [switch]$NoVerify
    )

    if ($Help) { Show-Help; exit 0 }

    $platform  = Get-Platform
    $assetName = Resolve-Asset -Platform $platform

    $tmpDir = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName())
    New-Item -ItemType Directory -Path $tmpDir | Out-Null

    try {
{{- if .Hooks.PrePs1}}
        # gpipe test: pre-install-hook
        # Pre-install hook injected from config at generation time.
        # Available variables: $script:GithubRepo, $script:Version, $script:Binary, $script:InstallName
        & {
{{.Hooks.PrePs1}}
        }
{{- end}}

        Invoke-DownloadAsset -TmpDir $tmpDir -AssetName $assetName
        Confirm-Signature     -TmpDir $tmpDir -NoVerify $NoVerify.IsPresent
        Confirm-Checksum      -TmpDir $tmpDir -AssetName $assetName

        $resolvedInstall = Resolve-InstallDir -UserInstall $User.IsPresent -NoVerify $NoVerify.IsPresent
        $installDir = $resolvedInstall.Path
        Install-Binary -TmpDir $tmpDir -AssetName $assetName -InstallDir $installDir

{{- if .Completions.PowerShell}}
        Install-Completion -InstallDir $installDir
{{- end}}

{{- if .Hooks.PostPs1}}
        # gpipe test: post-install-hook
        # Post-install hook injected from config at generation time.
        # Available variables: $script:GithubRepo, $script:Version, $script:Binary,
        #                      $script:InstallName, $installDir
        & {
{{.Hooks.PostPs1}}
        }
{{- end}}

        Update-Path -InstallDir $installDir -UserInstall $resolvedInstall.IsUserInstall

        Write-Ok "Successfully installed $script:InstallName $script:Version"

    } finally {
        if ($tmpDir -and (Test-Path $tmpDir)) {
            Remove-Item -Recurse -Force $tmpDir -ErrorAction SilentlyContinue
        }
    }
}

# Guard: run only when executed directly, not when dot-sourced for testing.
# Parameters are bound by the script-level param() block at the top of the file.
if ($MyInvocation.InvocationName -ne '.') {
    try {
        Invoke-Installer -User:$User -Help:$Help -NoVerify:$NoVerify
    } catch {
        # Exit-Error already prints a formatted [ERROR] line for expected
        # failures before throwing. This catch is the backstop for everything
        # else (unhandled .NET exceptions, cmdlet errors) so the installer
        # never dies with no output at all. It goes through Write-Label rather
        # than Exit-Error, which would throw a second time from inside a catch.
        Write-Label -Label '[ERROR]' -Colour Red -Msg "$_"
        exit 1
    }
}
