# Generated by gpipe: https://github.com/thomaslaurenson/gpipe
# Do not edit manually. Re-generate with: gpipe generate --repo <owner/repo> --version <vX.Y.Z>

param(
    [switch]$User,
    [switch]$Help,
    [switch]$NoVerify
)

$ErrorActionPreference = "Stop"
$ProgressPreference    = "SilentlyContinue"

# ============================================================
# CONSTANTS: baked in at generation time
# ============================================================
$GithubRepo  = "{{.GithubRepo}}"
$Version     = "{{.Version}}"
$Binary      = "{{.Binary}}"
$InstallName = "{{.InstallName}}"

# ============================================================
# OUTPUT HELPERS
# ============================================================
$NoColor = ($null -ne $env:NO_COLOR)

function Write-Info  { param($Msg) if ($script:NoColor) { Write-Host "[INFO]  $Msg"  } else { Write-Host "[INFO]  " -ForegroundColor Green  -NoNewline; Write-Host $Msg } }
function Write-Warn  { param($Msg) if ($script:NoColor) { Write-Host "[WARN]  $Msg"  } else { Write-Host "[WARN]  " -ForegroundColor Yellow -NoNewline; Write-Host $Msg } }
function Write-Step  { param($Msg) if ($script:NoColor) { Write-Host "  > $Msg"      } else { Write-Host "  > "     -ForegroundColor Cyan   -NoNewline; Write-Host $Msg } }
function Exit-Error  {
    param($Msg)
    if ($script:NoColor) { Write-Host "[ERROR] $Msg" } else { Write-Host "[ERROR] " -ForegroundColor Red -NoNewline; Write-Host $Msg }
    exit 1
}

# ============================================================
# USAGE
# ============================================================
function Show-Help {
    Write-Host @"
${InstallName} installer

USAGE:
  .\install.ps1 [-User] [-NoVerify] [-Help]

OPTIONS:
  -User       Install to user directory (no elevation required)
              Default path: $env:LOCALAPPDATA\Programs\${InstallName}
  -NoVerify   Skip cosign signature verification on checksums.txt
              By default, the installer verifies the release signature
              using cosign. Use this flag only if cosign is unavailable.
              Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/
  -Help       Show this help message

EXAMPLES:
  # System-wide install (default, prompts for elevation if not Administrator)
  .\install.ps1

  # User install, no elevation needed
  .\install.ps1 -User

  # Skip cosign verification (not recommended)
  .\install.ps1 -NoVerify

  # Piped user install
  Invoke-WebRequest -Uri "https://github.com/${GithubRepo}/releases/download/${Version}/install.ps1" ``
    -OutFile install.ps1; .\install.ps1 -User

"@
}

if ($Help) { Show-Help; exit 0 }

# ============================================================
# PLATFORM DETECTION
# Use PROCESSOR_ARCHITECTURE env vars for compatibility with PowerShell 5.1+.
# PROCESSOR_ARCHITEW6432 is set when a 32-bit process runs on a 64-bit OS.
# ============================================================
$OSArch = $env:PROCESSOR_ARCHITECTURE
if ($env:PROCESSOR_ARCHITEW6432) { $OSArch = $env:PROCESSOR_ARCHITEW6432 }

$NormArch = switch ($OSArch) {
    "AMD64" { "amd64" }
    "ARM64" { "arm64" }
    default { Exit-Error "Unsupported architecture: $OSArch" }
}

$Platform = "windows_${NormArch}"

# ============================================================
# ASSET MAP: baked in at generation time
# Maps platform identifier to GitHub release asset filename.
# ============================================================
$AssetNames = @{
{{- range .Platforms}}
  "{{.ID}}" = "{{.AssetName}}"{{- end}}
}

if (-not $AssetNames.ContainsKey($Platform)) {
    $supported = ($AssetNames.Keys | Where-Object { $_ -like "windows_*" }) -join ", "
    Exit-Error "Unsupported platform: $Platform. Supported: $supported"
}

$AssetName       = $AssetNames[$Platform]
$DownloadUrl     = "https://github.com/$GithubRepo/releases/download/$Version/$AssetName"
$ChecksumsUrl    = "https://github.com/$GithubRepo/releases/download/$Version/checksums.txt"
$ChecksumsSigUrl = "https://github.com/$GithubRepo/releases/download/$Version/checksums.txt.sigstore.json"

{{- if .Hooks.PrePs1}}
# ============================================================
# PRE-INSTALL HOOK
# Injected from config at generation time.
# Available variables: $GithubRepo, $Version, $Binary, $InstallName
# Note: $ErrorActionPreference = "Stop" is active; any terminating
# error in the hook will abort the installer.
# ============================================================
# --- gpipe: pre-install hook ---
& {
{{.Hooks.PrePs1}}
}
# --- gpipe: end pre-install hook ---
{{- end}}

# ============================================================
# DOWNLOAD
# ============================================================
$TmpDir = Join-Path ([System.IO.Path]::GetTempPath()) ([System.IO.Path]::GetRandomFileName())
New-Item -ItemType Directory -Path $TmpDir | Out-Null

try {
    Write-Info "Downloading $Binary $Version for $Platform..."
    Write-Step  $DownloadUrl

    try {
        Invoke-WebRequest -Uri $DownloadUrl     -OutFile "$TmpDir\$AssetName"                  -UseBasicParsing -TimeoutSec 60
    } catch {
        Exit-Error "Failed to download ${AssetName}: $_"
    }

    try {
        Invoke-WebRequest -Uri $ChecksumsUrl    -OutFile "$TmpDir\checksums.txt"               -UseBasicParsing -TimeoutSec 30
    } catch {
        Exit-Error "Failed to download checksums.txt: $_"
    }

    try {
        Invoke-WebRequest -Uri $ChecksumsSigUrl -OutFile "$TmpDir\checksums.txt.sigstore.json" -UseBasicParsing -TimeoutSec 30
    } catch {
        Exit-Error "Failed to download checksums.txt.sigstore.json: $_"
    }

    # ============================================================
    # COSIGN SIGNATURE VERIFICATION
    # Verifies checksums.txt was produced by the official release
    # workflow before trusting any checksum values.
    # Use -NoVerify to skip (not recommended).
    # ============================================================
    if ($NoVerify) {
        Write-Warn "Skipping cosign signature verification (-NoVerify passed)"
    } else {
        if (-not (Get-Command cosign -ErrorAction SilentlyContinue)) {
            Exit-Error @"
cosign not found in PATH.

  The installer verifies release signatures by default to ensure
  the download has not been tampered with. cosign is required for this.

  Install cosign: https://docs.sigstore.dev/cosign/system_config/installation/

  To skip verification (not recommended):
    .\install.ps1 -NoVerify
"@
        }
        Write-Info "Verifying cosign signature on checksums.txt..."
        cosign verify-blob `
            --bundle "$TmpDir\checksums.txt.sigstore.json" `
            --certificate-identity-regexp="https://github.com/{{.GithubRepo}}/.github/workflows/.*" `
            --certificate-oidc-issuer="https://token.actions.githubusercontent.com" `
            "$TmpDir\checksums.txt"
        if ($LASTEXITCODE -ne 0) { Exit-Error "cosign signature verification failed" }
        Write-Step "Cosign signature OK"
    }

    # ============================================================
    # CHECKSUM VERIFICATION
    # Verifies the downloaded binary against the (now trusted) checksums.txt.
    # The two-space separator is part of the sha256sum format.
    # Both hashes are lowercased before comparison for consistency.
    # ============================================================
    Write-Info "Verifying checksum..."
    $ChecksumLine = Get-Content "$TmpDir\checksums.txt" |
        Where-Object { $_ -like "*  $AssetName" }

    if (-not $ChecksumLine) {
        Exit-Error "Checksum not found for $AssetName in checksums.txt"
    }

    $ExpectedHash = ($ChecksumLine -split "\s+")[0].ToLower()
    $ActualHash   = (Get-FileHash -Algorithm SHA256 "$TmpDir\$AssetName").Hash.ToLower()

    if ($ExpectedHash -ne $ActualHash) {
        Exit-Error "Checksum mismatch for ${AssetName}:`n  expected: $ExpectedHash`n  actual:   $ActualHash"
    }
    Write-Step "Checksum OK"

    # ============================================================
    # INSTALL
    # ============================================================
    $UserInstall = $User.IsPresent
    $InstallDir  = ""

    if ($UserInstall) {
        $InstallDir = "$env:LOCALAPPDATA\Programs\$InstallName"
    } else {
        $SystemDir = "$env:ProgramFiles\$InstallName"
        $IsAdmin   = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(
                        [Security.Principal.WindowsBuiltInRole]::Administrator)

        if ($IsAdmin) {
            $InstallDir = $SystemDir
        } else {
            if ([Environment]::UserInteractive) {
                Write-Host ""
                Write-Host "Insufficient permissions to install to $SystemDir" -ForegroundColor Yellow
                Write-Host ""
                Write-Host "  1) Re-run as Administrator (opens elevated prompt)"
                Write-Host "  2) Install to $env:LOCALAPPDATA\Programs\$InstallName (no elevation)"
                Write-Host "  3) Quit"
                Write-Host ""
                $Choice = Read-Host "Choose [1/2/3]"

                switch ($Choice.Trim()) {
                    "1" {
                        if (-not [string]::IsNullOrEmpty($PSCommandPath)) {
                            Write-Info "Launching elevated session..."
                            $ArgList = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
                            Start-Process powershell -Verb RunAs -ArgumentList $ArgList -Wait
                            exit 0
                        } else {
                            Write-Host "[ERROR] Cannot auto-elevate: save install.ps1 to disk first, then run from an elevated prompt:" -ForegroundColor Red
                            Write-Host "          powershell -File .\install.ps1"
                            exit 1
                        }
                    }
                    "2" {
                        $UserInstall = $true
                        $InstallDir  = "$env:LOCALAPPDATA\Programs\$InstallName"
                    }
                    default { Exit-Error "Installation aborted." }
                }
            } else {
                Write-Host "[ERROR] Insufficient permissions to install to $SystemDir" -ForegroundColor Red
                Write-Host ""
                Write-Host "To install in an elevated PowerShell session, download and run:"
                Write-Host "  Invoke-WebRequest -Uri `"https://github.com/$GithubRepo/releases/download/$Version/install.ps1`" -OutFile install.ps1"
                Write-Host "  Start-Process powershell -Verb RunAs -ArgumentList `"-File .\install.ps1`" -Wait"
                Write-Host ""
                Write-Host "To install without elevation (user install):"
                Write-Host "  Invoke-WebRequest -Uri `"https://github.com/$GithubRepo/releases/download/$Version/install.ps1`" -OutFile install.ps1"
                Write-Host "  .\install.ps1 -User"
                exit 1
            }
        }
    }

    if (-not (Test-Path $InstallDir)) {
        New-Item -ItemType Directory -Path $InstallDir | Out-Null
    }
    Copy-Item "$TmpDir\$AssetName" "$InstallDir\$InstallName.exe" -Force
    Write-Info "Installed $InstallName to $InstallDir\$InstallName.exe"

    # ============================================================
    # SHELL COMPLETIONS
    # Included when enabled in .gpipe.yml.
    # ============================================================
{{- if .Completions.PowerShell}}
    try {
        $CompletionOutput = & "$InstallDir\$InstallName.exe" completion powershell 2>&1
        if ($LASTEXITCODE -eq 0) {
            # Ensure $PROFILE exists before appending
            $ProfileDir = Split-Path $PROFILE
            if (-not (Test-Path $ProfileDir)) { New-Item -ItemType Directory -Path $ProfileDir | Out-Null }
            if (-not (Test-Path $PROFILE))    { New-Item -ItemType File      -Path $PROFILE    | Out-Null }
            $Marker  = "# $Binary completions (added by gpipe)"
            $Content = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
            if (-not $Content -or $Content -notmatch [regex]::Escape($Marker)) {
                Add-Content -Path $PROFILE -Value "`n$Marker`n$CompletionOutput"
                Write-Step "PowerShell completions → $PROFILE"
            }
        } else {
            Write-Warn "PowerShell completion not available from ${InstallName}: binary may not support the completion subcommand"
        }
    } catch {
        Write-Warn "PowerShell completion generation failed, skipping: $_"
    }
{{- end}}

    # ============================================================
    # POST-INSTALL HOOK
    # Injected from config at generation time.
    # Available variables: $GithubRepo, $Version, $Binary, $InstallName, $InstallDir
    # Note: $ErrorActionPreference = "Stop" is active; any terminating
    # error in the hook will abort the installer.
    # ============================================================
{{- if .Hooks.PostPs1}}
    # --- gpipe: post-install hook ---
    & {
        {{.Hooks.PostPs1}}
    }
    # --- gpipe: end post-install hook ---
{{- end}}

    # ============================================================
    # PATH MANAGEMENT
    # ============================================================
    if ($UserInstall) {
        $UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
        if ($UserPath -notlike "*$InstallDir*") {
            [Environment]::SetEnvironmentVariable("PATH", "$InstallDir;$UserPath", "User")
            Write-Warn "Added $InstallDir to user PATH. Restart your terminal for the change to take effect."
        }
    } else {
        $env:PATH = "$InstallDir;$env:PATH"
        if (-not (Get-Command $InstallName -ErrorAction SilentlyContinue)) {
            Write-Warn "$InstallName is not reachable via PATH: $InstallDir may need to be added manually"
        }
    }

    Write-Info "Successfully installed $InstallName $Version"

} finally {
    # Clean up temp directory, guarding against it never being created
    if ($TmpDir -and (Test-Path $TmpDir)) {
        Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
    }
}
